### ISSUE TITLE
GLIBC_2.39 not found

### ISSUE THREAD

**Issue by pythoncoder83** [SpiralP/classicube-cef-loader-plugin#60]
when i start classicube with cef, this error shows up:
![Screenshot from 2024-11-01 17-12-24](https://github.com/user-attachments/assets/c27bf28e-c5f4-45d0-a9e2-fd68d9a8bc9e)
and cef doesnt load
os: linux x86_64

**Comment by Goldegag37** [comment]
exact same here.

**Comment by epicgamer1234** [comment]
same here
![Screenshot from 2024-11-06 07-39-54](https://github.com/user-attachments/assets/883837b3-a22e-4cd3-97b8-efcfc0bd4fd5)

**Comment by Goldegag37** [comment]
seems to be a debian issue.
(I switched to arch and it works for me)

**Comment by pythoncoder83** [comment]
It has been seemingly fixed since a recent update.
