### ISSUE TITLE
libssl.so.1.1 cannot open shared object file no such file or directory

### ISSUE THREAD

**Issue by idksomeone0** [SpiralP/classicube-cef-loader-plugin#8]
![image](https://user-images.githubusercontent.com/96211138/220454978-cd3d83db-7732-452a-850b-90f1d85fa023.png)

**Comment by SpiralP** [comment]
updated to use libssl3 in this version https://github.com/SpiralP/classicube-cef-loader-plugin/releases/tag/v1.2.0
